stateをserialサービスとplayviewmodelで分けた
p2hacks2024/post-04 pull request #5
Opened 2024-12-12 11:40 UTC by tauto1127

2024-12-12 18:40 UTC, uwatcha requested changes
やったで〜

2024-12-12 18:40 UTC, uwatcha commented on flutter/lib/model/enums/arduino_message_type_enum.dart
> +  static const String ready = 'PWR';
他に倣って
`powerOn = 'PWR'`
のようにすべき？

2024-12-12 18:40 UTC, uwatcha commented on flutter/lib/service/foreground_serial_service.dart
> +    connectAttemptTimer = Timer.periodic(const Duration(seconds: 1), (timer) async {
このDurationの目的は？
開発中の都合によるものならスルーOK

2024-12-12 18:40 UTC, uwatcha commented on flutter/lib/viewmodel/play_view_model.dart
> +import 'package:epsilon_app/model/enums/arduino_message_type_enum.dart';
ディレクトリ名
`viewmodel`から
`view_model`にしたい

2024-12-12 22:00 UTC, tauto1127 commented on flutter/lib/service/foreground_serial_service.dart
> +    connectAttemptTimer = Timer.periodic(const Duration(seconds: 1), (timer) async {
これは接続試行タイマーです

2024-12-13 01:05 UTC, uwatcha approved these changes

2024-12-13 01:05 UTC, merged